# Generated by Django 5.1.3 on 2025-02-06 16:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_otp_user_otp_created_at_user_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_image', models.CharField(blank=True, max_length=255, null=True)),
                ('specialization', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('appointment_fees', models.CharField()),
                ('experience', models.IntegerField(default=0)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('diagnostics', 'Diagnostics & Imaging'), ('medical_checkups', 'Medical Checkups & Screenings'), ('emergency', 'Emergency & Critical Care'), ('therapy', 'Physiotherapy & Rehabilitation')], max_length=50)),
                ('available_24x7', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('cardiology', 'Cardiology Treatments'), ('neurology', 'Neurology Treatments'), ('orthopedic', 'Orthopedic Treatments'), ('oncology', 'Cancer Treatments'), ('surgery', 'General Surgery'), ('maternity', 'Maternity & Childbirth')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_fees_in_hospital', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('specialization_in_hospital', models.CharField(max_length=255)),
                ('consultation_days', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_management.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_slots', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospital')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_management.service')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('doctor_required', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospital')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_management.treatment')),
            ],
        ),
    ]
