# Generated by Django 5.1.5 on 2025-02-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldoctor',
            name='consultation_days',
            field=models.CharField(default='Monday to Friday', max_length=255),
        ),
        migrations.AlterField(
            model_name='hospitaldoctor',
            name='specialization_in_hospital',
            field=models.CharField(default='General', max_length=255),
        ),
    ]
