# Generated by Django 5.1.5 on 2025-02-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management', '0002_alter_hospitaldoctor_consultation_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldoctor',
            name='availability_in_hospital',
            field=models.BooleanField(default=True),
        ),
    ]
