# Generated by Django 5.1.5 on 2025-02-11 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management', '0003_hospitaldoctor_availability_in_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalservice',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='hospitaltreatment',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
