# Generated by Django 5.1.5 on 2025-02-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billhistory',
            name='status',
            field=models.CharField(choices=[], max_length=10),
        ),
    ]
