# Generated by Django 5.1.5 on 2025-02-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_contactus_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='location',
            new_name='hospital_address',
        ),
    ]
