# Generated by Django 5.1.5 on 2025-02-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_location_hospital_hospital_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
